package PlataformaVentas;


import clases.Conexion;
import org.w3c.dom.Element;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

/**
 *
 * @author The_S
 */
public class ConsultaMP extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();

    public ConsultaMP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultaMPFrame = new javax.swing.JLayeredPane();
        panelConsultaMP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOC = new javax.swing.JTextField();
        btnConsultaOC = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblDireccionEmpresa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRutEmpresa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNombreContacto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblRutComprador = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblDireccionDemandante = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFechaCreacionOC = new javax.swing.JLabel();
        lblNombreDemandante = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTelefonoDemandante = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblNombreOrdenCompra = new javax.swing.JLabel();
        lblFechaEntregaProducto = new javax.swing.JLabel();
        lblDireccionEnvioFactura = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblContactoPago = new javax.swing.JLabel();
        lblMetodoDespacho = new javax.swing.JLabel();
        lblFormaPago = new javax.swing.JLabel();
        lblContactoOC = new javax.swing.JLabel();
        lblEmailEnvioFactura = new javax.swing.JLabel();
        lblDireccionDespacho = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblDescripcionOrden = new javax.swing.JLabel();
        btnGuardarOrden = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        lblUnidadCompra = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblImpuestoEspecifico = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotalDcto = new javax.swing.JLabel();
        lblTotalCargos = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblTotalNeto = new javax.swing.JLabel();
        txtObservacionDespacho = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        btnVolver7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblEstadoOrdenCompra = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        lblFondoConsultaMP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelConsultaMP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Código de Orden de Compra:");

        btnConsultaOC.setText("Consultar");
        btnConsultaOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaOCActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Proveedor:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Rut:");

        jLabel8.setText("Información de la empresa:");

        jLabel9.setText("Nombre de Contacto:");

        jLabel10.setText("Fono:");

        jLabel11.setText("Rut de Comprador:");

        jLabel12.setText("Dirección Demandante:");

        jLabel13.setText("Demandante:");

        jLabel14.setText("Fecha de Envio OC:");

        jLabel16.setText("Teléfono:");

        lblTelefonoDemandante.setToolTipText("");

        jLabel17.setText("Información de Demandante:");

        jLabel18.setText("Información de Orden:");

        jLabel19.setText("Nombre de Orden de Compra:");

        jLabel20.setText("Fecha de Entrega Productos:");

        jLabel21.setText("Direcciones de Despacho:");

        jLabel22.setText("Dirección de Envío de factura:");

        lblNombreOrdenCompra.setText("-");

        lblFechaEntregaProducto.setText("-");

        lblDireccionEnvioFactura.setText("-");

        jLabel23.setText("Metodo de Despacho:");

        jLabel24.setText("Contacto de Pago:");

        jLabel25.setText("Forma de Pago:");

        jLabel26.setText("Contacto OC:");

        jLabel27.setText("Mail de envío de factura:");

        lblContactoPago.setText("-");

        lblMetodoDespacho.setText("-");

        lblFormaPago.setText("-");

        lblContactoOC.setText("-");

        lblEmailEnvioFactura.setText("-");

        lblDireccionDespacho.setText("-");

        jLabel32.setText("Observación de Orden:");

        lblDescripcionOrden.setText("-");

        btnGuardarOrden.setText("Guardar Orden");
        btnGuardarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarOrdenActionPerformed(evt);
            }
        });

        jLabel33.setText("Unidad de Compra:");

        tblMP = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código / ID Licitación CM", "Producto", "Cantidad", "Especificación de Comprador", "Especificación de Proveedor", "Moneda", "Precio Unitario", "Descuento", "Cargos", "Valor Total"
            }
        ));
        jScrollPane4.setViewportView(tblMP);

        jTabbedPane1.addTab("Información de Productos", jScrollPane4);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel28.setText("Neto:");

        jLabel29.setText("Dcto:");

        jLabel30.setText("Cargos:");

        jLabel31.setText("Subtotal:");

        jLabel34.setText("19% IVA:");

        jLabel35.setText("Impuesto Especifico:");

        jLabel36.setText("Total:");

        lblImpuestoEspecifico.setText("-");

        lblTotal.setText("-");

        lblIva.setText("-");

        lblTotalDcto.setText("-");

        lblTotalCargos.setText("-");

        lblSubTotal.setText("-");

        lblTotalNeto.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel34)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalDcto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIva, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImpuestoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 908, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalNeto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblTotalDcto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lblTotalCargos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(lblImpuestoEspecifico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(lblTotal))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Totales", jPanel2);

        jLabel62.setText("Observación de Despacho:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel27))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmailEnvioFactura)
                                        .addComponent(lblDireccionEnvioFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel21))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNombreOrdenCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDireccionDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFechaEntregaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel17)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(25, 25, 25)
                                    .addComponent(lblRutComprador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel16))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblDireccionDemandante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTelefonoDemandante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRutEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDireccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContactoOC, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMetodoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContactoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNombreDemandante, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel33))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(3, 3, 3)
                                                    .addComponent(lblUnidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblFechaCreacionOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNombreContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDescripcionOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtObservacionDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblRutComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDireccionDemandante, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefonoDemandante, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33)
                                    .addComponent(lblUnidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(lblFechaCreacionOC, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblNombreDemandante, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDireccionEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFono, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRutEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lblMetodoDespacho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(lblContactoPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblFormaPago)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lblNombreOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(lblFechaEntregaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDireccionDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(lblContactoOC)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(lblDireccionEnvioFactura))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblEmailEnvioFactura))
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionOrden)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacionDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(btnGuardarOrden))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        btnVolver7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnVolver7.setText("Volver");
        btnVolver7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver7ActionPerformed(evt);
            }
        });

        jLabel15.setText("Estado de cotización:");

        jLabel167.setForeground(new java.awt.Color(204, 0, 0));
        jLabel167.setText("Solo se recibirán ordenes de compra en estado de \"Aceptada\"");

        javax.swing.GroupLayout panelConsultaMPLayout = new javax.swing.GroupLayout(panelConsultaMP);
        panelConsultaMP.setLayout(panelConsultaMPLayout);
        panelConsultaMPLayout.setHorizontalGroup(
            panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaMPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaMPLayout.createSequentialGroup()
                        .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelConsultaMPLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConsultaOC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultaMPLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEstadoOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(545, 545, 545)
                                .addComponent(btnVolver7))
                            .addGroup(panelConsultaMPLayout.createSequentialGroup()
                                .addComponent(jLabel167)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelConsultaMPLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(3, 3, 3))
        );
        panelConsultaMPLayout.setVerticalGroup(
            panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultaMPLayout.createSequentialGroup()
                .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaMPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver7)
                            .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGroup(panelConsultaMPLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(lblEstadoOrdenCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsultaMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultaOC)
                    .addComponent(jLabel167))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );

        lblFondoConsultaMP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelConsultaMPFrameLayout = new javax.swing.GroupLayout(panelConsultaMPFrame);
        panelConsultaMPFrame.setLayout(panelConsultaMPFrameLayout);
        panelConsultaMPFrameLayout.setHorizontalGroup(
            panelConsultaMPFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaMPFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultaMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblFondoConsultaMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelConsultaMPFrameLayout.setVerticalGroup(
            panelConsultaMPFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoConsultaMP, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultaMPFrameLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(panelConsultaMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConsultaMPFrame.setLayer(panelConsultaMP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelConsultaMPFrame.setLayer(lblFondoConsultaMP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultaMPFrame, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultaMPFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaOCActionPerformed

        try {

            //Consulta de BD
            //En esta sección se ingresa el Request para que la "API", digamosle así xd y posteriormente entrega el resultado del mismo.
            String format = "xml";
            String url = "http://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.xml?codigo=" + txtOC.getText().toUpperCase() + "&ticket=210555F9-8B7E-48ED-93ED-2504CAD3B155";
            System.out.println(url);
            //Se crea un obj de tipo url con el cual se realizará el request
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            int responseCode = con.getResponseCode();
            //Por motivos de Debug, se necesita el codigo de respuesta
            System.out.println("Código de Respuesta : " + responseCode);
            StringBuffer response;
            try (BufferedReader in = new BufferedReader(
                    new InputStreamReader(con.getInputStream()))) {
                String inputLine;
                response = new StringBuffer();
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
            }
            //print in String
            // System.out.println(response.toString());
            org.w3c.dom.Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new InputSource(new StringReader(response.toString())));
            //Aqui segun el TAG del XML va a poder obtener los elementos...
            //Obedeciendo el orden del documento, los tags son los siguientes...

            NodeList ordenes = doc.getElementsByTagName("Ordenes");
            if (ordenes.getLength() > 0) {
                Element err = (Element) ordenes.item(0);
                lblFechaCreacionOC.setText((err.getElementsByTagName("FechaCreacion").item(0).getTextContent()));
                lblEstadoOrdenCompra.setText(err.getElementsByTagName("Estado").item(0).getTextContent());
                lblUnidadCompra.setText(err.getElementsByTagName("NombreUnidad").item(0).getTextContent());

            } else {
                // success
            }

            NodeList comprador = doc.getElementsByTagName("Comprador");
            if (comprador.getLength() > 0) {
                Element err = (Element) comprador.item(0);
                lblRutComprador.setText(err.getElementsByTagName("RutUnidad").item(0).getTextContent());
                lblDireccionDemandante.setText(err.getElementsByTagName("DireccionUnidad").item(0).getTextContent());
                lblNombreDemandante.setText(err.getElementsByTagName("NombreOrganismo").item(0).getTextContent());
                lblTelefonoDemandante.setText(err.getElementsByTagName("FonoContacto").item(0).getTextContent());
            } else {
                // success
            }

            NodeList proveedor = doc.getElementsByTagName("Proveedor");
            if (proveedor.getLength() > 0) {
                Element err = (Element) proveedor.item(0);
                lblProveedor.setText(err.getElementsByTagName("Nombre").item(0).getTextContent());
                lblDireccionEmpresa.setText(err.getElementsByTagName("Direccion").item(0).getTextContent());
                lblRutEmpresa.setText(err.getElementsByTagName("RutSucursal").item(0).getTextContent());
                lblNombreContacto.setText(err.getElementsByTagName("NombreContacto").item(0).getTextContent());
                lblFono.setText(err.getElementsByTagName("FonoContacto").item(0).getTextContent());
            } else {
                // success
            }

            NodeList detalleOrden = doc.getElementsByTagName("OrdenCompra");
            if (detalleOrden.getLength() > 0) {
                Element err = (Element) detalleOrden.item(0);
                lblNombreOrdenCompra.setText(err.getElementsByTagName("Nombre").item(0).getTextContent());
                lblDireccionDespacho.setText(err.getElementsByTagName("DireccionUnidad").item(0).getTextContent() + " "
                        + err.getElementsByTagName("ComunaUnidad").item(0).getTextContent() + " " + err.getElementsByTagName("RegionUnidad").item(0).getTextContent());
                lblDireccionEnvioFactura.setText(err.getElementsByTagName("DireccionUnidad").item(0).getTextContent() + " "
                        + err.getElementsByTagName("ComunaUnidad").item(0).getTextContent() + " "
                        + err.getElementsByTagName("RegionUnidad").item(0).getTextContent());
                lblMetodoDespacho.setText(err.getElementsByTagName("TipoDespacho").item(0).getTextContent());
                lblContactoPago.setText(err.getElementsByTagName("NombreContacto").item(0).getTextContent() + " "
                        + err.getElementsByTagName("FonoContacto").item(0).getTextContent() + " "
                        + err.getElementsByTagName("MailContacto").item(0).getTextContent());
                lblFormaPago.setText(err.getElementsByTagName("FormaPago").item(0).getTextContent());
                lblContactoOC.setText(err.getElementsByTagName("NombreContacto").item(0).getTextContent());
                lblEmailEnvioFactura.setText(err.getElementsByTagName("MailContacto").item(0).getTextContent());

            } else {
                // success
            }
            DefaultTableModel model = (DefaultTableModel) tblMP.getModel();
            NodeList flowList = doc.getElementsByTagName("Item");
            for (int i = 0; i < flowList.getLength(); i++) {
                model.setRowCount(flowList.getLength());
                tblMP.setModel(model);
                NodeList childList = flowList.item(i).getChildNodes();
                for (int j = 0; j < childList.getLength(); j++) {
                    Node childNode = childList.item(j);
                    if ("CodigoProducto".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 0);
                    }
                    if (null != childNode.getNodeName()) {
                        switch (childNode.getNodeName()) {
                            case "Producto":
                                tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                        .trim(), i, 1);
                                break;
                            case "EspecificacionComprador":
                                tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                        .trim(), i, 1);
                                break;
                        }
                    }
                    if ("Cantidad".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 2);
                    }
                    if ("EspecificacionComprador".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 3);
                    }
                    if ("EspecificacionProveedor".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 4);
                    }
                    if ("Moneda".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 5);
                    }
                    if ("PrecioNeto".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 6);
                    }
                    if ("TotalDescuentos".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 7);
                    }
                    if ("TotalCargos".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 8);
                    }
                    if ("Total".equals(childNode.getNodeName())) {
                        tblMP.getModel().setValueAt(childList.item(j).getTextContent()
                                .trim(), i, 9);
                    }
                }
            }

            NodeList detalleMontos = doc.getElementsByTagName("OrdenCompra");
            if (detalleMontos.getLength() > 0) {
                Element err = (Element) detalleMontos.item(0);
                lblTotalNeto.setText("$" + err.getElementsByTagName("TotalNeto").item(0).getTextContent());
                lblTotalDcto.setText("$" + err.getElementsByTagName("Descuentos").item(0).getTextContent());
                lblTotalCargos.setText("$" + err.getElementsByTagName("Cargos").item(0).getTextContent());
                //setSubTotal(Integer.parseInt(getTotalNeto()) -Integer.parseInt(getTotalDcto()));
                lblIva.setText("$" + err.getElementsByTagName("Impuestos").item(0).getTextContent());
                lblImpuestoEspecifico.setText("$" + err.getElementsByTagName("TotalImpuestos").item(0).getTextContent());
                lblTotal.setText("$" + err.getElementsByTagName("Total").item(0).getTextContent());

            } else {
                // success
            }
            NodeList descripcion = doc.getElementsByTagName("OrdenCompra");
            if (descripcion.getLength() > 0) {
                Element err = (Element) descripcion.item(0);
                lblDescripcionOrden.setText(err.getElementsByTagName("Descripcion").item(0).getTextContent());
            } else {
                // success
            }
            System.out.println("La consulta fue realizada con éxito");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnConsultaOCActionPerformed

    private void btnGuardarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarOrdenActionPerformed
        try {
            if (!"Aceptada".equals(lblEstadoOrdenCompra.getText())) {
                JOptionPane.showMessageDialog(null, "La orden de compra no se encuentra aceptada");
            } else {

                if (txtObservacionDespacho.getText().equals(null) || txtObservacionDespacho.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Observación de despacho se encuentra vacía.");
                } else {
                    String msgConfirmacion = JOptionPane.showInputDialog("Ingrese Código de Autorización");
                    String validar = msgConfirmacion;
                    int selectedRows = tblMP.getRowCount();
                    String query = "INSERT INTO `acimabasededatos`.`ordendecompra` "
                            + "(`codigoOrdenCompra`,`nombre_proveedor`, "
                            + "`rutCliente`, `DireccionDemandante`, "
                            + "`Telefono`, `Demandante`,"
                            + " `UnidadCompra`, `fechaEnvioOC`, `codigoEstado`, `nombreOrdenCompra`, "
                            + "`fechaEntregaProductos`, `direccionesDespacho`, `direccionEnvioFactura`,"
                            + "`idtipoDespacho`, `contactoPago`, `idformaPago`, `contactoOC`,`emailEnvioFactura`,`moneda`,`neto`,"
                            + " `dcto`, `subtotal`,`iva`, `impuestoEspecifico`, `total`,`observacionDespacho`,`codigo_autorizacion`) "
                            + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pst;
                    pst = cn.prepareStatement(query);
                    pst.setString(1, txtOC.getText().toUpperCase());
                    pst.setString(2, lblProveedor.getText());
                    pst.setString(3, lblRutComprador.getText());
                    pst.setString(4, lblDireccionDemandante.getText());
                    pst.setString(5, lblTelefonoDemandante.getText());
                    pst.setString(6, lblNombreDemandante.getText());
                    pst.setString(7, lblUnidadCompra.getText());
                    pst.setString(8, lblFechaCreacionOC.getText());
                    pst.setString(9, lblEstadoOrdenCompra.getText());
                    pst.setString(10, lblNombreOrdenCompra.getText());
                    pst.setString(11, lblFechaEntregaProducto.getText());
                    pst.setString(12, lblDireccionDespacho.getText());
                    pst.setString(13, lblDireccionEnvioFactura.getText());
                    pst.setString(14, lblMetodoDespacho.getText());
                    pst.setString(15, lblContactoPago.getText());
                    pst.setString(16, lblFormaPago.getText());
                    pst.setString(17, lblContactoOC.getText());
                    pst.setString(18, lblEmailEnvioFactura.getText());
                    pst.setString(19, (tblMP.getValueAt(0, 5).toString()));
                    pst.setString(20, lblTotalNeto.getText());
                    pst.setString(21, lblTotalDcto.getText());
                    pst.setString(22, lblSubTotal.getText());
                    pst.setString(23, lblIva.getText());
                    pst.setString(24, lblImpuestoEspecifico.getText());
                    pst.setString(25, lblTotal.getText());
                    pst.setString(26, txtObservacionDespacho.getText());
                    pst.setInt(27, Integer.parseInt(validar));
                    int up = pst.executeUpdate();
                    for (int i = 0; i < selectedRows; i++) {
                        String sub = tblMP.getValueAt(i, 1).toString();
                        sub = sub.substring(sub.indexOf("(") + 1);
                        sub = sub.substring(0, sub.indexOf(")"));
                        System.out.println(sub);
                        String queryDetalle = "INSERT INTO `acimabasededatos`.`detalleordencompra` (`codigoOrdenCompra`,`codigoProducto`,`nombreProducto`,`cantidad`,`precioUnitario`,`descuento`,`cargos`,`valorTotal`) VALUES(?,?,?,?,?,?,?,?);";
                        PreparedStatement pstDetalle = cn.prepareStatement(queryDetalle);
                        pstDetalle.setString(1, txtOC.getText().toUpperCase());
                        pstDetalle.setString(2, sub);
                        pstDetalle.setString(3, (tblMP.getValueAt(i, 1).toString()));
                        pstDetalle.setString(4, (tblMP.getValueAt(i, 2).toString()));
                        pstDetalle.setString(5, (tblMP.getValueAt(i, 6).toString()));
                        pstDetalle.setString(6, (tblMP.getValueAt(i, 7).toString()));
                        pstDetalle.setString(7, (tblMP.getValueAt(i, 8).toString()));
                        pstDetalle.setString(8, (tblMP.getValueAt(i, 9).toString()));
                        int upDetalle = pstDetalle.executeUpdate();

                    }
                    JOptionPane.showMessageDialog(null, "Se ha ingresado la siguiente orden de compra: " + txtOC.getText().toUpperCase());

                    lblFechaCreacionOC.setText("");
                    lblEstadoOrdenCompra.setText("");
                    lblUnidadCompra.setText("");
                    lblRutComprador.setText("");
                    lblDireccionDemandante.setText("");
                    lblNombreDemandante.setText("");
                    lblTelefonoDemandante.setText("");
                    lblNombreOrdenCompra.setText("");
                    lblDireccionDespacho.setText("");
                    lblDireccionEnvioFactura.setText("");
                    lblMetodoDespacho.setText("");
                    lblContactoPago.setText("");
                    lblFormaPago.setText("");
                    lblContactoOC.setText("");
                    lblEmailEnvioFactura.setText("");
                    lblTotalNeto.setText("");
                    lblTotalDcto.setText("");
                    lblTotalCargos.setText("");
                    lblSubTotal.setText("");
                    lblIva.setText("");
                    lblImpuestoEspecifico.setText("");
                    lblTotal.setText("");

                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex);
        }
    }//GEN-LAST:event_btnGuardarOrdenActionPerformed

    private void btnVolver7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaMP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaMP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaMP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaMP.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaOC;
    private javax.swing.JButton btnGuardarOrden;
    private javax.swing.JButton btnVolver7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblContactoOC;
    private javax.swing.JLabel lblContactoPago;
    private javax.swing.JLabel lblDescripcionOrden;
    private javax.swing.JLabel lblDireccionDemandante;
    private javax.swing.JLabel lblDireccionDespacho;
    private javax.swing.JLabel lblDireccionEmpresa;
    private javax.swing.JLabel lblDireccionEnvioFactura;
    private javax.swing.JLabel lblEmailEnvioFactura;
    private javax.swing.JLabel lblEstadoOrdenCompra;
    private javax.swing.JLabel lblFechaCreacionOC;
    private javax.swing.JLabel lblFechaEntregaProducto;
    private javax.swing.JLabel lblFondoConsultaMP;
    private javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblFormaPago;
    private javax.swing.JLabel lblImpuestoEspecifico;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblMetodoDespacho;
    private javax.swing.JLabel lblNombreContacto;
    private javax.swing.JLabel lblNombreDemandante;
    private javax.swing.JLabel lblNombreOrdenCompra;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblRutComprador;
    private javax.swing.JLabel lblRutEmpresa;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTelefonoDemandante;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalCargos;
    private javax.swing.JLabel lblTotalDcto;
    private javax.swing.JLabel lblTotalNeto;
    private javax.swing.JLabel lblUnidadCompra;
    private javax.swing.JPanel panelConsultaMP;
    private javax.swing.JLayeredPane panelConsultaMPFrame;
    private javax.swing.JTable tblMP;
    public javax.swing.JTextField txtOC;
    private javax.swing.JTextField txtObservacionDespacho;
    // End of variables declaration//GEN-END:variables
}
