/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlataformaVentas;

import clases.Conexion;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Diego
 */
public class DatosCotizacion extends javax.swing.JFrame {

    /**
     * Creates new form DatosCotizacion
     */
    Conexion con = new Conexion();
    Connection cn = con.conecta();

    public DatosCotizacion() {
        initComponents();
     //   BtnGuardar.setEnabled(false);
        //  btnImprimir.setEnabled(false);
        lblCiudad.setVisible(false);
        lblCorreoUsuario.setVisible(false);
        lblDireccion.setVisible(false);
        lblNombre.setVisible(false);
        lblRazon.setVisible(false);
        lblUsuario.setVisible(false);
        tblRecolecionPDF.setVisible(false);
    }

    public PdfPCell getCell(String text, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(0);
        cell.setHorizontalAlignment(alignment);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNeto = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lbRut = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbNeto = new javax.swing.JLabel();
        lbIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lbrazonsociall = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecolecionPDF = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCorreoUsuario = new javax.swing.JLabel();
        lblRazon = new javax.swing.JLabel();
        lbDistribuidor = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDistribuidor = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lblIDUsuario = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Cotización");
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRut.setEditable(false);
        txtRut.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        getContentPane().add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 270, -1));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 270, -1));

        txtNeto.setEditable(false);
        txtNeto.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        txtNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 270, -1));

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });
        getContentPane().add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 270, -1));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 270, -1));

        txtRazonSocial.setEditable(false);
        txtRazonSocial.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        getContentPane().add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 270, -1));

        txtCargo.setEditable(false);
        txtCargo.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        getContentPane().add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 270, -1));

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 270, -1));

        lbRut.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbRut.setText("Rut");
        getContentPane().add(lbRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lbNombre.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbNombre.setText("Nombre");
        getContentPane().add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lbNeto.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbNeto.setText("Neto");
        getContentPane().add(lbNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        lbIVA.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbIVA.setText("IVA");
        getContentPane().add(lbIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        lblTotal.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblTotal.setText("Total");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        lbrazonsociall.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbrazonsociall.setText("Razón Social");
        getContentPane().add(lbrazonsociall, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lbCargo.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbCargo.setText("Cargo");
        getContentPane().add(lbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lbStatus.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbStatus.setText("Status");
        getContentPane().add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        lbFecha.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbFecha.setText("Fecha Emisión");
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        BtnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 270, 50));

        btnImprimir.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnImprimir.setText("Imprimir y guardar");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 270, 50));

        cbStatus.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Respondido", "Respondido" }));
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 270, -1));

        tblRecolecionPDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecolecionPDF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 0, 0));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Titulo.setText("Actualización Cotización");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));
        getContentPane().add(lblCorreoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));
        getContentPane().add(lblRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        lbDistribuidor.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lbDistribuidor.setText("Distribuidor");
        getContentPane().add(lbDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        txtDistribuidor.setEditable(false);
        txtDistribuidor.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        txtDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistribuidorActionPerformed(evt);
            }
        });
        getContentPane().add(txtDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 270, -1));
        getContentPane().add(lblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        tblDetalle = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalle);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 970, 160));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/BlancoGrande.png"))); // NOI18N
        fondo.setPreferredSize(new java.awt.Dimension(825, 500));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        lbCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        lblIDUsuario.setText("jLabel14");
        getContentPane().add(lblIDUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        txtID.setEditable(false);
        txtID.setText("jTextField1");
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 0, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetoActionPerformed

    private void Acusador() {
        String id = lblIDUsuario.getText();
        String respuesta = JOptionPane.showInputDialog(null, "Escriba Su codigo de autorización.", "Permisos de acción", JOptionPane.INFORMATION_MESSAGE);
        if (lbCodigo.getText().equals(respuesta)) {
            JOptionPane.showMessageDialog(null, "Codigo de autorización Correcto.", "Correcto", JOptionPane.INFORMATION_MESSAGE);

            try {
                String Comentario = "El usuario nro. " + id + " a modificado la cotizacion con la id nro. " + txtID.getText();

                String query = "INSERT INTO movimientosventas (IDUsuario,Movimiento) VALUES (?,?)";
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(lblIDUsuario.getText()));
                pst.setString(2, Comentario);
                int up = pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Codigo de autorizacion invalido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        ActualizarCotizacion();
        //Metodo para Escoger la ruta donde se guardara el reporte
        String ruta = "";

        JFileChooser dlg = new JFileChooser();
        dlg.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int option = dlg.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            ruta = f.toString();
        }
        //Obetener datos para la tabla
        try {
            String ID = txtID.getText();
            String query = "Select producto.ID AS 'ID de Producto',\n"
                    + "conveniomarco.NombreConvenio AS 'Convenio Marco',\n"
                    + "producto.categoria AS 'Nombre Producto',\n"
                    + "producto.SKU AS 'SKU',\n"
                    + "cotizacion.Precio AS 'Precio',\n"
                    + "cotizacion.Cantidad AS 'Cantidad',\n"
                    + "cotizacion.Descuento AS 'Descuento',\n"
                    + "cotizacion.Cargo AS 'Cargo'\n"
                    + "FROM cotizacion JOIN producto ON cotizacion.ID = producto.ID\n"
                    + "JOIN conveniomarco ON producto.CodigoConvenio = conveniomarco.codigoConvenio\n"
                    + "WHERE cotizacion.IDCotizacion=?";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, ID);
            ResultSet rs = pst.executeQuery();
            tblRecolecionPDF.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //obtener datos para pdf
        try {
            String ID = txtID.getText();
            String query = "SELECT cliente.Nombre,\n"
                    + "usuario.NombreUsuario,\n"
                    + "usuario.CorreoUsuario,\n"
                    + "cliente.Razon_social,\n"
                    + "cliente.Direccion,\n"
                    + "cliente.Ciudad\n"
                    + "from cotizacion JOIN usuario ON cotizacion.IDUsuario = usuario.IDUsuario\n"
                    + "JOIN cliente ON cotizacion.IDCliente = cliente.IDCliente\n"
                    + "WHERE cotizacion.IDCotizacion = ? ";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, ID);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                lblNombre.setText(rs.getString("Nombre"));
                lblUsuario.setText(rs.getString("NombreUsuario"));
                lblCorreoUsuario.setText(rs.getString("CorreoUsuario"));
                lblRazon.setText(rs.getString("Razon_social"));
                lblDireccion.setText(rs.getString("Direccion"));
                lblCiudad.setText(rs.getString("Ciudad"));
            }
        } catch (Exception e) {
        }

        //Fecha
        Date sistFecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd-MMM-YYYY");

        //Crear PDF
        try {
            Document doc = new Document(PageSize.A4);
            try {
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                Calendar calendar = Calendar.getInstance();

                Date sistHora = new Date();
                String pmAm = "hh:mm a";
                SimpleDateFormat format = new SimpleDateFormat(pmAm);
                Calendar hoy = Calendar.getInstance();
                String hora = (String.format(format.format(sistHora), hoy));
                hora.replace(':', '-');

                PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(ruta + "\\" + lblNombre.getText() + "_Fecha_" + formato.format(sistFecha) + "_hora_" + hora + "_Cotizacion_" + txtID.getText() + ".pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormularioCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            String input = "src\\plataformaVentas\\Imagenes\\acima-logo-200p.png";
            try {
                doc.add(Image.getInstance(input));
            } catch (BadElementException ex) {
                Logger.getLogger(FormularioCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FormularioCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            Paragraph header = new Paragraph("Para cualquier duda relacionada con la siguiente cotizacion, favor contactar a :", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(header);
            Paragraph header2 = new Paragraph("Ejecutivo de Cuenta: " + lblUsuario.getText() + " Correo:" + lblCorreoUsuario.getText() + " Telefono: +56 2 3210 7900", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(header2);
            Paragraph separacion = new Paragraph("________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
            doc.add(separacion);
            Paragraph titulo = new Paragraph("Información de Cliente", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(titulo);

            PdfPTable tableDatos = new PdfPTable(2);
            tableDatos.setWidthPercentage(100);
            tableDatos.addCell(getCell("Razón Social: " + lblRazon.getText(), PdfPCell.ALIGN_LEFT));
            tableDatos.addCell(getCell("Rut: " + txtRut.getText(), PdfPCell.ALIGN_RIGHT));
            doc.add(tableDatos);

            PdfPTable tableDatos2 = new PdfPTable(2);
            tableDatos2.setWidthPercentage(100);
            tableDatos2.addCell(getCell("Dirección: " + lblDireccion.getText(), PdfPCell.ALIGN_LEFT));

            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            Calendar calendar = Calendar.getInstance();

            tableDatos2.addCell(getCell("Fecha de Cotizacion: " + simpleDateFormat.format(calendar.getTime()), PdfPCell.ALIGN_RIGHT));
            doc.add(tableDatos2);

            PdfPTable tableDatos3 = new PdfPTable(2);
            tableDatos3.setWidthPercentage(100);
            tableDatos3.addCell(getCell("Ciudad: " + lblCiudad.getText(), PdfPCell.ALIGN_LEFT));
            tableDatos3.addCell(getCell("Atención a: " + lblNombre.getText(), PdfPCell.ALIGN_RIGHT));
            doc.add(tableDatos3);
            Paragraph separacion2 = new Paragraph("________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
            doc.add(separacion2);
            Paragraph tablas = new Paragraph("Información de Cotizacion ", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(tablas);
            try {

                PdfPTable pdfTable = new PdfPTable(tblDetalle.getColumnCount());
                //Parámetros de espaciado y ancho
                pdfTable.setSpacingBefore(15f);
                pdfTable.setWidthPercentage(100);
                //Añadir Valores
                for (int i = 0; i < tblDetalle.getColumnCount(); i++) {
                    pdfTable.addCell(new Phrase(tblDetalle.getColumnName(i), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                }
                //Extraer valores de la Jtable al PDF
                for (int rows = 0; rows < tblDetalle.getRowCount(); rows++) {
                    for (int cols = 0; cols < tblDetalle.getColumnCount(); cols++) {
                        pdfTable.addCell(new Phrase(tblDetalle.getModel().getValueAt(rows, cols).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    }
                }

                //Metodo antiguo, porfavor no borrar
                /* pdfTable.setTotalWidth(PageSize.A3.getWidth());
                 pdfTable.setLockedWidth(true);
                 PdfContentByte canvas = writer.getDirectContent();
                 PdfTemplate template = canvas.createTemplate(
                 pdfTable.getTotalWidth(), pdfTable.getTotalHeight());
                 pdfTable.writeSelectedRows(0, -1, 0, pdfTable.getTotalHeight(), template);
                 Image img = Image.getInstance(template);
                 img.scaleToFit(PageSize.A3.getWidth(), PageSize.A3.getHeight());
                 img.setAbsolutePosition(1, (PageSize.A3.getHeight() - pdfTable.getTotalHeight()) / 1.6f);
                 */
                Paragraph bruto = new Paragraph("Neto: $" + txtNeto.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                bruto.setAlignment(Paragraph.ALIGN_RIGHT);
                Paragraph iva = new Paragraph("IVA: $" + txtIva.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                iva.setAlignment(Paragraph.ALIGN_RIGHT);
                Paragraph neto = new Paragraph("Total: $" + txtTotal.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                neto.setAlignment(Paragraph.ALIGN_RIGHT);
                doc.add(pdfTable);
                doc.add(bruto);
                doc.add(iva);
                doc.add(neto);
                Paragraph nota = new Paragraph("Esta cotización debe ser respondida dentro de 15 días hábiles", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                doc.add(nota);
                doc.close();
            } catch (DocumentException ex) {

            }

            JOptionPane.showMessageDialog(null, "PDF Generado Correctamente");

        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void ActualizarCotizacion() {
        try {
            String iva = txtIva.getText();
            String Neto = txtNeto.getText();
            String Total = txtTotal.getText();
            String ID = txtID.getText();
            String status;
            if (cbStatus.getSelectedIndex() == 0) {
                status = "No Respondido";
            } else {
                status = "Respondido";
            }

            String query = "UPDATE cotizacion SET Bruto = ?, IvaTotal = ?, NetoTotal = ?, Respondido = ?, fechaCotizacion = CURRENT_TIMESTAMP WHERE IDCotizacion = ?;";
            PreparedStatement update = cn.prepareStatement(query);
            update.setString(1, Total);
            update.setString(2, iva);
            update.setString(3, Neto);
            update.setString(4, status);
            update.setString(5, ID);
            int u = update.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed

        ActualizarCotizacion();
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void txtDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistribuidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistribuidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosCotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnImprimir;
    public static javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCargo;
    public javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDistribuidor;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbIVA;
    private javax.swing.JLabel lbNeto;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbRut;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCorreoUsuario;
    private javax.swing.JLabel lblDireccion;
    public javax.swing.JLabel lblIDUsuario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRazon;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lbrazonsociall;
    public javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblRecolecionPDF;
    public javax.swing.JTextField txtCargo;
    public javax.swing.JTextField txtDistribuidor;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtIva;
    public javax.swing.JTextField txtNeto;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtRazonSocial;
    public javax.swing.JTextField txtRut;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
