package PlataformaVentas;

import clases.Conexion;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Diego Alfaro Fierro, Diego González Romàn
 */
public class FormularioCotizacion extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();
    private double[][] data;
    DefaultTableModel model;

    public FormularioCotizacion() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jPanel3.setBackground(new Color(0, 0, 0, 30));

        Date sistFecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MMM/YYYY");
        txtFecha.setText(formato.format(sistFecha));
        lblUsuario.setVisible(false);
        btnGuardaPDF.setEnabled(true);
        btnCalcular.setEnabled(false);

        model = new DefaultTableModel();
        tblCalculos.setModel(model);
        model.addColumn("");
        model.addColumn("");
        model.addRow(new Object[]{"Neto"});
        model.addRow(new Object[]{"IVA"});
        model.addRow(new Object[]{"Cargo"});
        model.addRow(new Object[]{"Descuento %"});
        model.addRow(new Object[]{"Total"});
        tblCalculos.setModel(model);

        lblIDCliente.setVisible(false);
        lblBrutoTotal.setVisible(false);
        lblNetoTotal.setVisible(false);
        lblIVATotal.setVisible(false);
    }

    public PdfPCell getCell(String text, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(0);
        cell.setHorizontalAlignment(alignment);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        panelDatos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCorporacion = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblRazon = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUnidadDeCompra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCotizacion = new javax.swing.JTable();
        btnGuardaPDF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCalculos = new javax.swing.JTable();
        txtRut = new javax.swing.JFormattedTextField();
        b_Titulo = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        lblIDUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNetoTotal = new javax.swing.JLabel();
        lblIDCliente = new javax.swing.JLabel();
        lblBrutoTotal = new javax.swing.JLabel();
        lblIVATotal = new javax.swing.JLabel();
        lblCredencial = new javax.swing.JLabel();
        lblCorreoUsuario = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel1.setText("Nombre");

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel2.setText("Correo");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel7.setText("Entidad");

        lblCorporacion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        lblCargo.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel8.setText("Cargo");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel10.setText("Razon Social");

        lblRazon.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel12.setText("U. de Compra");

        lblUnidadDeCompra.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel14.setText("Telefono");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel16.setText("Región");

        lblRegion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel20.setText("Ciudad");

        lblCiudad.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        lblComuna.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel21.setText("Direccion");

        lblDireccion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel18.setText("Comuna");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel11.setText("Fecha de Cotización");

        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComuna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lblCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(lblComuna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblCorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(lblRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(lblUnidadDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatos.addTab("Informacion de Cliente", jPanel1);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 740));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 740));

        tblCotizacion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblCotizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCotizacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblCotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID de Producto", "Convenio Marco", "Nombre Producto", "SKU", "Precio", "Cantidad", "Descuento", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCotizacion);

        btnGuardaPDF.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnGuardaPDF.setText("Guardar Cotización y generar PDF");
        btnGuardaPDF.setActionCommand("");
        btnGuardaPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaPDFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel3.setText("Rut:");

        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnCalcular.setText("Calcular Precios");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        tblCalculos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblCalculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCalculos.setToolTipText("");
        tblCalculos.setRowSelectionAllowed(false);
        tblCalculos.getTableHeader().setResizingAllowed(false);
        tblCalculos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblCalculos);
        if (tblCalculos.getColumnModel().getColumnCount() > 0) {
            tblCalculos.getColumnModel().getColumn(0).setResizable(false);
            tblCalculos.getColumnModel().getColumn(1).setResizable(false);
        }

        try {
            txtRut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-H")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRut.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRutKeyPressed(evt);
            }
        });

        b_Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b_Titulo.setText("Realizar Cotización");

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo.setText("Generar Cotización");

        lblNetoTotal.setVisible(false);
        lblNetoTotal.setText("0");

        lblBrutoTotal.setVisible(false);
        lblBrutoTotal.setText("0");

        lblIVATotal.setVisible(false);
        lblIVATotal.setText("0");

        lblCredencial.setVisible(false);
        lblCredencial.setText("jLabel4");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/acima-logo-400p.png"))); // NOI18N
        jLabel4.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                                    .addComponent(panelDatos)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnGuardaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCalcular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBrutoTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIVATotal)
                                .addGap(18, 18, 18)
                                .addComponent(lblNetoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(b_Titulo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(Titulo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(429, 429, 429))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(921, 921, 921)
                                    .addComponent(lblCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(811, 811, 811)
                                    .addComponent(lblIDUsuario))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(905, 905, 905)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(865, 865, 865)
                                    .addComponent(lblIDCliente)))
                            .addGap(40, 40, 40)
                            .addComponent(lblCredencial))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(1242, 1242, 1242)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescuento, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap(653, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(b_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo)))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNetoTotal)
                        .addComponent(lblIVATotal)
                        .addComponent(lblBrutoTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardaPDF)
                        .addComponent(btnCalcular)
                        .addComponent(jButton1)))
                .addGap(0, 0, 0))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblIDUsuario)
                                    .addGap(3, 3, 3)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblIDCliente)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblCredencial)))
                            .addGap(368, 368, 368)
                            .addComponent(lblDescuento)
                            .addGap(276, 276, 276))
                        .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(368, Short.MAX_VALUE)))
        );

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/BackgroundNew.png"))); // NOI18N

        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(lblFondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(lblFondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardaPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaPDFActionPerformed
        //Metodo para Escoger la ruta donde se guardara el reporte
        String ruta = "";

        JFileChooser dlg = new JFileChooser();
        dlg.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int option = dlg.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            ruta = f.toString();
        }

//INSERTAR EN BASE DE DATOS     
        try {
            int idCliente = 0;
            int idUsuario = 0;
            int up2;
            idUsuario = Integer.parseInt(lblIDUsuario.getText());
            String query2 = "INSERT INTO movimientosventas(`IDUsuario`, `Movimiento`) VALUES (?,'Realizar Cotización')";
            PreparedStatement pst2 = cn.prepareStatement(query2);
            pst2.setInt(1, idUsuario);
            up2 = pst2.executeUpdate();

            TableModel modelo = tblCotizacion.getModel();
            int selectedRows = tblCotizacion.getRowCount();
            String query = "INSERT INTO cotizacion (`ID`, `IDUsuario`, `IDCliente`, `Precio`, `Cantidad`, `Bruto`, `iva_debito`, `neto`,`Descuento`,`Cargo` ,`Respondido`) VALUES ((SELECT ID FROM producto WHERE IDproducto = ?),?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement pst = cn.prepareStatement(query);
            //idProducto
            pst.setInt(1, Integer.parseInt(tblCotizacion.getValueAt(0, 0).toString()));
            //idUsuario
            pst.setInt(2, Integer.parseInt(lblIDUsuario.getText()));
            //idCliente
            pst.setInt(3, Integer.parseInt(lblIDCliente.getText()));
            //precio
            pst.setInt(4, Integer.parseInt(tblCotizacion.getValueAt(0, 4).toString()));
            //cantidad
            pst.setInt(5, Integer.parseInt(tblCotizacion.getValueAt(0, 5).toString()));
            //Bruto
            pst.setInt(6, Integer.parseInt(tblCalculos.getValueAt(0, 1).toString()));
            //IVA
            pst.setInt(7, Integer.parseInt(tblCalculos.getValueAt(4, 1).toString()));
            //NETO
            pst.setInt(8, Integer.parseInt(tblCalculos.getValueAt(5, 1).toString()));
            //Descuento
            pst.setDouble(9, Double.parseDouble(tblCotizacion.getValueAt(0, 6).toString()));
            //Cargo
            pst.setInt(10, Integer.parseInt(tblCotizacion.getValueAt(0, 7).toString()));
            //Estado No Respondido
            pst.setString(11, "No Respondido");

            int up = pst.executeUpdate();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        //Fecha
        Date sistFecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd-MMM-YYYY");
        //Crear PDF
        try {
            Document doc = new Document(PageSize.A4);
            try {
                PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(ruta + "\\" + lblNombre.getText() + formato.format(sistFecha) + ".pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormularioCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            String input = "src\\plataformaVentas\\Imagenes\\acima-logo-200p.png";
            try {
                doc.add(Image.getInstance(input));
            } catch (BadElementException ex) {
                Logger.getLogger(FormularioCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FormularioCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            Paragraph header = new Paragraph("Para cualquier duda relacionada con la siguiente cotizacion, favor contactar a :", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(header);
            Paragraph header2 = new Paragraph("Ejecutivo de Cuenta: " + lblUsuario.getText() + " Correo:" + lblCorreoUsuario.getText() + " Telefono: +56 2 3210 7900", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(header2);
            Paragraph separacion = new Paragraph("________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
            doc.add(separacion);
            Paragraph titulo = new Paragraph("Información de Cliente", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(titulo);

            PdfPTable tableDatos = new PdfPTable(2);
            tableDatos.setWidthPercentage(100);
            tableDatos.addCell(getCell("Razón Social: " + lblRazon.getText(), PdfPCell.ALIGN_LEFT));
            tableDatos.addCell(getCell("Rut: " + txtRut.getText(), PdfPCell.ALIGN_RIGHT));
            doc.add(tableDatos);

            PdfPTable tableDatos2 = new PdfPTable(2);
            tableDatos2.setWidthPercentage(100);
            tableDatos2.addCell(getCell("Dirección: " + lblDireccion.getText(), PdfPCell.ALIGN_LEFT));
            tableDatos2.addCell(getCell("Fecha de Cotizacion: " + txtFecha.getText(), PdfPCell.ALIGN_RIGHT));
            doc.add(tableDatos2);

            PdfPTable tableDatos3 = new PdfPTable(2);
            tableDatos3.setWidthPercentage(100);
            tableDatos3.addCell(getCell("Ciudad: " + lblCiudad.getText(), PdfPCell.ALIGN_LEFT));
            tableDatos3.addCell(getCell("Atención a: " + lblNombre.getText(), PdfPCell.ALIGN_RIGHT));
            doc.add(tableDatos3);
            Paragraph separacion2 = new Paragraph("________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
            doc.add(separacion2);
            Paragraph tablas = new Paragraph("Información de Cotizacion ", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(tablas);
            try {

                PdfPTable pdfTable = new PdfPTable(tblCotizacion.getColumnCount());
                //Parámetros de espaciado y ancho
                pdfTable.setSpacingBefore(15f);
                pdfTable.setWidthPercentage(100);
                //Añadir Valores
                for (int i = 0; i < tblCotizacion.getColumnCount(); i++) {
                    pdfTable.addCell(tblCotizacion.getColumnName(i));
                }
                //Extraer valores de la Jtable al PDF
                for (int rows = 0; rows < tblCotizacion.getRowCount(); rows++) {
                    for (int cols = 0; cols < tblCotizacion.getColumnCount(); cols++) {
                        pdfTable.addCell(tblCotizacion.getModel().getValueAt(rows, cols).toString());
                    }
                }
                //Metodo antiguo, porfavor no borrar
                /* pdfTable.setTotalWidth(PageSize.A3.getWidth());
                 pdfTable.setLockedWidth(true);
                 PdfContentByte canvas = writer.getDirectContent();
                 PdfTemplate template = canvas.createTemplate(
                 pdfTable.getTotalWidth(), pdfTable.getTotalHeight());
                 pdfTable.writeSelectedRows(0, -1, 0, pdfTable.getTotalHeight(), template);
                 Image img = Image.getInstance(template);
                 img.scaleToFit(PageSize.A3.getWidth(), PageSize.A3.getHeight());
                 img.setAbsolutePosition(1, (PageSize.A3.getHeight() - pdfTable.getTotalHeight()) / 1.6f);
                 */
                Paragraph neto = new Paragraph("Neto: $" + lblNetoTotal.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                neto.setAlignment(Paragraph.ALIGN_RIGHT);
                Paragraph iva = new Paragraph("IVA: $" + lblIVATotal.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                iva.setAlignment(Paragraph.ALIGN_RIGHT);
                Paragraph bruto = new Paragraph("Total: $" + lblTotal.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                bruto.setAlignment(Paragraph.ALIGN_RIGHT);
                doc.add(pdfTable);
                doc.add(bruto);
                doc.add(iva);
                doc.add(neto);
                Paragraph nota = new Paragraph("Esta cotización debe ser respondida dentro de 15 días hábiles", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                doc.add(nota);
                doc.close();
            } catch (DocumentException ex) {

            }

            JOptionPane.showMessageDialog(null, "PDF Generado Correctamente");

        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardaPDFActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String query = "SELECT `IDCliente`, region.`nombreRegion`, comuna.`NombreComuna`, `Rut`, `Nombre`, org.nombreOrganizacion,u.detalle, `Cargo`, `Razon_social`, `Correo`, `Telefono`, `Ciudad`, `Direccion`, `fechaIngreso` FROM `cliente` join region on cliente.IDRegion = region.IDRegion join comuna on comuna.IDComuna = cliente.IDComuna join organizacion org on org.idOrganizacion=cliente.idOrganizacion join unidaddecompra u on u.idunidadcompra=cliente.idunidadcompra WHERE cliente.rut=?";
            String param = txtRut.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                lblIDCliente.setText(rs.getString("IDCliente"));
                lblNombre.setText(rs.getString("Nombre"));
                lblCorreo.setText(rs.getString("Correo"));
                lblCorporacion.setText(rs.getString("nombreOrganizacion"));
                lblUnidadDeCompra.setText(rs.getString("u.detalle"));
                lblCargo.setText(rs.getString("Cargo"));
                lblRazon.setText(rs.getString("Razon_Social"));
                lblTelefono.setText(rs.getString("Telefono"));
                lblRegion.setText(rs.getString("region.nombreRegion"));
                lblComuna.setText(rs.getString("comuna.nombreComuna"));
                lblCiudad.setText(rs.getString("Ciudad"));
                lblDireccion.setText(rs.getString("Direccion"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        btnCalcular.setEnabled(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int selectedRows[] = tblCotizacion.getSelectedRows();
        /*
         Calculos Diego
         */
        int cantidad;
        /*descuento del precio total en double*/
        double descuento = 0;

        /*Cargo que se le hara al totalFinal*/
        int cargo;

        /*descuento en numeros entre 0=0descuento y 1=100 por ciento de descuento*/
        double descuentoPorcentaje;

        /*precio que sera descontado*/
        double precioDescuento;

        /*precio que sera descontado*/
        int precioDescuento_Entero;

        /*Precio Producto*/
        int precio;

        /*Cantidad * Precio*/
        int Neto = 0;

        /*Total con descuento = Neto-precioDescuento_Entero */
        int precioConDescuento = 0;
        /*Neto*0.19*/
        double IVA;
        /*Neto*0.19*/
        int IVA_entero = 0;
        /*Neto+iva+cargo+precioDescuento*/
        int TotalFinal = 0;
        /*
         Fin Calculos Diego
         */

        if (tblCotizacion.getSelectedRow() >= 0) {
            for (int i : selectedRows) {
                String cant = JOptionPane.showInputDialog("Ingrese Cantidad para Producto: ");
                cantidad = Integer.parseInt(cant);
                tblCotizacion.getModel().setValueAt(cantidad, tblCotizacion.getSelectedRow(), 5);

                //Metodo para Descuento
                String dcto = JOptionPane.showInputDialog("Ingrese Descuento: ");
                descuento = Double.parseDouble(dcto);
                tblCotizacion.getModel().setValueAt(descuento, tblCotizacion.getSelectedRow(), 6);

                //Metodo para Cargo
                String carg = JOptionPane.showInputDialog("Ingrese Cargo: ");
                cargo = Integer.parseInt(carg);
                tblCotizacion.getModel().setValueAt(cargo, tblCotizacion.getSelectedRow(), 7);

                if (descuento == 0 && cargo == 0 || descuento == 0 || cargo == 0) {
                    precio = Integer.parseInt(tblCotizacion.getValueAt(i, 4).toString());

                    descuentoPorcentaje = descuento / 100;

                    precioDescuento = precio * descuentoPorcentaje;
                    precioDescuento_Entero = (int) precioDescuento;
                    precioConDescuento = precio - precioDescuento_Entero;

                    Neto = precioConDescuento * cantidad;

                    IVA = Neto * 0.19;
                    IVA_entero = (int) IVA;

                    TotalFinal = Neto + IVA_entero + cargo;

                    if (tblCalculos.getColumnCount() >= tblCotizacion.getRowCount()) {

                        model.removeRow(0);
                        model.removeRow(1);
                        model.removeRow(2);
                        model.removeRow(3);
                        model.removeRow(4);
                        model.removeRow(5);

                        tblCalculos.setModel(model);

                        model.addRow(new Object[]{"Neto", Neto});
                        model.addRow(new Object[]{"IVA", IVA_entero});
                        model.addRow(new Object[]{"Cargo", cargo});
                        model.addRow(new Object[]{"Descuento %", descuento});
                        model.addRow(new Object[]{"Total", TotalFinal});
                    } else {

                        JOptionPane.showMessageDialog(null, "La tabla se reiniciará");

                        model.removeRow(0);
                        model.removeRow(1);
                        model.removeRow(2);
                        model.removeRow(3);
                        model.removeRow(4);
                        model.removeRow(5);

                        tblCalculos.setModel(model);

                        model.addRow(new Object[]{"Neto", Neto});
                        model.addRow(new Object[]{"IVA", IVA_entero});
                        model.addRow(new Object[]{"Cargo", cargo});
                        model.addRow(new Object[]{"Descuento %", descuento});
                        model.addRow(new Object[]{"Total", TotalFinal});
                    }

                } else {
                    precio = Integer.parseInt(tblCotizacion.getValueAt(i, 4).toString());
                    descuentoPorcentaje = descuento / 100;

                    precioDescuento = (precio * cantidad) * descuentoPorcentaje;
                    precioDescuento_Entero = (int) precioDescuento;
                    Neto = precio * cantidad;

                    precioConDescuento = Neto - precioDescuento_Entero;

                    IVA = Neto * 0.19;
                    IVA_entero = (int) IVA;

                    TotalFinal = Neto + IVA_entero + cargo;

                    if (tblCalculos.getColumnCount() >= tblCotizacion.getRowCount()) {
                        model.removeRow(0);
                        model.removeRow(0);
                        model.removeRow(0);
                        model.removeRow(0);
                        model.removeRow(0);
                        model.removeRow(0);

                        tblCalculos.setModel(model);

                        model.addRow(new Object[]{"Neto", Neto});
                        model.addRow(new Object[]{"IVA", IVA_entero});
                        model.addRow(new Object[]{"Cargo", cargo});
                        model.addRow(new Object[]{"Descuento %", descuento});
                        model.addRow(new Object[]{"Total", TotalFinal});
                    } else {
                        JOptionPane.showMessageDialog(null, "La tabla se reiniciará");

                        model.removeRow(0);
                        model.removeRow(1);
                        model.removeRow(2);
                        model.removeRow(3);
                        model.removeRow(4);
                        model.removeRow(5);

                        tblCalculos.setModel(model);

                        model.addRow(new Object[]{"Neto", Neto});
                        model.addRow(new Object[]{"IVA", IVA_entero});
                        model.addRow(new Object[]{"Cargo", cargo});
                        model.addRow(new Object[]{"Descuento %", descuento});
                        model.addRow(new Object[]{"Total", TotalFinal});
                    }
                }
            }

            lblDescuento.setText(descuento + "");
            lblIVATotal.setText(IVA_entero + "");
            lblNetoTotal.setText(Neto + "");
            lblTotal.setText(TotalFinal + "");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String query = "SELECT `IDCliente`, region.`nombreRegion`, comuna.`NombreComuna`, `Rut`, `Nombre`, org.nombreOrganizacion,u.detalle, `Cargo`, `Razon_social`, `Correo`, `Telefono`, `Ciudad`, `Direccion`, `fechaIngreso` FROM `cliente` join region on cliente.IDRegion = region.IDRegion join comuna on comuna.IDComuna = cliente.IDComuna join organizacion org on org.idOrganizacion=cliente.idOrganizacion join unidaddecompra u on u.idunidadcompra=cliente.idunidadcompra WHERE cliente.rut=?";
                String param = txtRut.getText();
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setString(1, param);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    lblIDCliente.setText(rs.getString("IDCliente"));
                    lblNombre.setText(rs.getString("Nombre"));
                    lblCorreo.setText(rs.getString("Correo"));
                    lblCorporacion.setText(rs.getString("nombreOrganizacion"));
                    lblUnidadDeCompra.setText(rs.getString("u.detalle"));
                    lblCargo.setText(rs.getString("Cargo"));
                    lblRazon.setText(rs.getString("Razon_Social"));
                    lblTelefono.setText(rs.getString("Telefono"));
                    lblRegion.setText(rs.getString("region.nombreRegion"));
                    lblComuna.setText(rs.getString("comuna.nombreComuna"));
                    lblCiudad.setText(rs.getString("Ciudad"));
                    lblDireccion.setText(rs.getString("Direccion"));
                }
                //JOptionPane.showMessageDialog(null, "LISTO");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            btnCalcular.setEnabled(true);
        }
    }//GEN-LAST:event_txtRutKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel b_Titulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGuardaPDF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrutoTotal;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblCorporacion;
    private javax.swing.JLabel lblCorreo;
    public javax.swing.JLabel lblCorreoUsuario;
    public javax.swing.JLabel lblCredencial;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIDCliente;
    public javax.swing.JLabel lblIDUsuario;
    private javax.swing.JLabel lblIVATotal;
    private javax.swing.JLabel lblNetoTotal;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRazon;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnidadDeCompra;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JTabbedPane panelDatos;
    private javax.swing.JTable tblCalculos;
    public javax.swing.JTable tblCotizacion;
    private javax.swing.JLabel txtFecha;
    public javax.swing.JFormattedTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
