package PlataformaVentas;

import clases.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Diego Alfaro Fierro, Diego González Romàn
 */
public class RecordatorioCotizaciones extends javax.swing.JFrame {

    /**
     * Creates new form Recordatorio
     */
    Conexion con = new Conexion();
    Connection cn = con.conecta();
    String queryTabla = "select rec.IDRecordatorio_cotizacion AS 'ID Recordatorio',\n"
            + "rec.IDCotizacion as 'ID cotización',\n"
            + "DATE_FORMAT(rec.fecha_recordatorioCobranza, '%d-%m-%Y') as 'Fecha Venc.',\n"
            + "rec.observacion as 'Observacion',\n"
            + "(CASE\n"
            + "WHEN rec.Estado = 1 THEN 'Por vencer'\n"
            + "WHEN rec.Estado = 2 THEN 'Realizado'\n"
            + "WHEN rec.Estado = 3 THEN 'Vencido'\n"
            + "END) AS 'Estado'\n"
            + "from recordatorio_cotizacion rec JOIN cotizacion cot on cot.IDCotizacion = rec.IDCotizacion\n"
            + "JOIN cliente cli ON cli.idCliente = cot.idCliente\n"
            + "JOIN organizacion org ON cli.IDOrganizacion = org.IDOrganizacion\n";

    public RecordatorioCotizaciones() {
        initComponents();

       
        jPanel2.setBackground(new Color(0, 0, 0, 30));

        jDateExacta.setVisible(true);
        jDateExacta.setEnabled(true);
        btn_Buscar_Exacto.setVisible(true);
        btn_Buscar_Exacto.setEnabled(true);
        JDateRango1.setVisible(false);
        JDateRango1.setEnabled(false);
        JDateRango2.setVisible(false);
        JDateRango2.setEnabled(false);
        btn_Buscar_Rango.setVisible(false);
        btn_Buscar_Rango.setEnabled(false);
        lbDesde.setVisible(false);
        lbHasta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        lb_Titulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblIDUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecordatorio = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cbCambiarEstado = new javax.swing.JComboBox<String>();
        btnCambiarEstado = new javax.swing.JButton();
        lbCodigo = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPnl_Cotización = new javax.swing.JPanel();
        ln_NroCotizacion = new javax.swing.JLabel();
        txt_NroCotizacion = new javax.swing.JTextField();
        jPnl_Fecha = new javax.swing.JPanel();
        jDateExacta = new com.toedter.calendar.JDateChooser();
        RdBtn_exacta = new javax.swing.JRadioButton();
        RdBtn_Rango = new javax.swing.JRadioButton();
        btn_Buscar_Exacto = new javax.swing.JButton();
        JDateRango1 = new com.toedter.calendar.JDateChooser();
        JDateRango2 = new com.toedter.calendar.JDateChooser();
        btn_Buscar_Rango = new javax.swing.JButton();
        lbDesde = new javax.swing.JLabel();
        lbHasta = new javax.swing.JLabel();
        jPnl_RespPen = new javax.swing.JPanel();
        lb_SubTituloEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<String>();
        jPnl_RutOrganizacion = new javax.swing.JPanel();
        lb_Rut = new javax.swing.JLabel();
        txt_Rut = new javax.swing.JTextField();
        jPnl_NombreCont = new javax.swing.JPanel();
        lb_NombreCon = new javax.swing.JLabel();
        txt_NombreCon = new javax.swing.JTextField();
        jPnl_Organizacion = new javax.swing.JPanel();
        lb_NombreOrg = new javax.swing.JLabel();
        txt_NombreOrg = new javax.swing.JTextField();
        lblVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recordatorios de Cotización");
        setMaximumSize(new java.awt.Dimension(1120, 740));
        setResizable(false);

        lb_Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lb_Titulo.setText("<html> <p align=\"center\">Recordatorios <br/>de <br/>Cotización</p>  </html>");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblIDUsuario.setVisible(false);

        tblRecordatorio = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblRecordatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecordatorio);

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbCambiarEstado.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        cbCambiarEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un estado", "Por Vencer", "Realizado", "Vencido" }));
        jPanel1.add(cbCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 270, -1));

        btnCambiarEstado.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnCambiarEstado.setText("Actualizar Estado");
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, -1));

        jTabbedPane1.addTab("Cambiar Estado", jPanel1);

        lbCodigo.setVisible(false);

        jTabbedPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ln_NroCotizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ln_NroCotizacion.setText("N° Cotización:");

        txt_NroCotizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_NroCotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NroCotizacionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_CotizaciónLayout = new javax.swing.GroupLayout(jPnl_Cotización);
        jPnl_Cotización.setLayout(jPnl_CotizaciónLayout);
        jPnl_CotizaciónLayout.setHorizontalGroup(
            jPnl_CotizaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_CotizaciónLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(ln_NroCotizacion)
                .addGap(18, 18, 18)
                .addComponent(txt_NroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_CotizaciónLayout.setVerticalGroup(
            jPnl_CotizaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_CotizaciónLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_CotizaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln_NroCotizacion)
                    .addComponent(txt_NroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Numero Cotización", jPnl_Cotización);

        jPnl_Fecha.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jPnl_Fecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateExacta.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jDateExacta.setMaxSelectableDate(new java.util.Date(253370779308000L));
        jPnl_Fecha.add(jDateExacta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 270, -1));

        buttonGroup1.add(RdBtn_exacta);
        RdBtn_exacta.setSelected(true);
        RdBtn_exacta.setText("Fecha Exacta");
        RdBtn_exacta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtn_exactaActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(RdBtn_exacta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        buttonGroup1.add(RdBtn_Rango);
        RdBtn_Rango.setText("Rango de Fechas");
        RdBtn_Rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtn_RangoActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(RdBtn_Rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        btn_Buscar_Exacto.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn_Buscar_Exacto.setText("Buscar");
        btn_Buscar_Exacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Buscar_ExactoActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(btn_Buscar_Exacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));

        JDateRango1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jPnl_Fecha.add(JDateRango1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 270, -1));

        JDateRango2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jPnl_Fecha.add(JDateRango2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 270, -1));

        btn_Buscar_Rango.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn_Buscar_Rango.setText("Buscar");
        btn_Buscar_Rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Buscar_RangoActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(btn_Buscar_Rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));

        lbDesde.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbDesde.setText("Desde:");
        jPnl_Fecha.add(lbDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lbHasta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbHasta.setText(" Hasta:");
        jPnl_Fecha.add(lbHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jTabbedPane2.addTab("Fecha Vencimiento", jPnl_Fecha);

        lb_SubTituloEstado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lb_SubTituloEstado.setText("Status de los Recordatorios:");

        cbEstado.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Por Vencer", "Realizado", "Vencido" }));
        cbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEstadoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPnl_RespPenLayout = new javax.swing.GroupLayout(jPnl_RespPen);
        jPnl_RespPen.setLayout(jPnl_RespPenLayout);
        jPnl_RespPenLayout.setHorizontalGroup(
            jPnl_RespPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_RespPenLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPnl_RespPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_SubTituloEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_RespPenLayout.setVerticalGroup(
            jPnl_RespPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_RespPenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_SubTituloEstado)
                .addGap(18, 18, 18)
                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane2.addTab("Status", jPnl_RespPen);

        lb_Rut.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lb_Rut.setText("Rut:");

        txt_Rut.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_RutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_RutOrganizacionLayout = new javax.swing.GroupLayout(jPnl_RutOrganizacion);
        jPnl_RutOrganizacion.setLayout(jPnl_RutOrganizacionLayout);
        jPnl_RutOrganizacionLayout.setHorizontalGroup(
            jPnl_RutOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_RutOrganizacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_Rut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPnl_RutOrganizacionLayout.setVerticalGroup(
            jPnl_RutOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_RutOrganizacionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_RutOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Rut)
                    .addComponent(txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Rut Organización", jPnl_RutOrganizacion);

        lb_NombreCon.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lb_NombreCon.setText("Nombre Contacto:");

        txt_NombreCon.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_NombreCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NombreConKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_NombreContLayout = new javax.swing.GroupLayout(jPnl_NombreCont);
        jPnl_NombreCont.setLayout(jPnl_NombreContLayout);
        jPnl_NombreContLayout.setHorizontalGroup(
            jPnl_NombreContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NombreContLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lb_NombreCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_NombreContLayout.setVerticalGroup(
            jPnl_NombreContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NombreContLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_NombreContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NombreCon)
                    .addComponent(txt_NombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nombre Contacto", jPnl_NombreCont);

        lb_NombreOrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lb_NombreOrg.setText("Nombre Organización:");

        txt_NombreOrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_NombreOrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NombreOrgKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_OrganizacionLayout = new javax.swing.GroupLayout(jPnl_Organizacion);
        jPnl_Organizacion.setLayout(jPnl_OrganizacionLayout);
        jPnl_OrganizacionLayout.setHorizontalGroup(
            jPnl_OrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_OrganizacionLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lb_NombreOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_NombreOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_OrganizacionLayout.setVerticalGroup(
            jPnl_OrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_OrganizacionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_OrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NombreOrg)
                    .addComponent(txt_NombreOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Organización", jPnl_Organizacion);

        lblVolver.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblVolver.setText("Volver");
        lblVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbCodigo)
                        .addComponent(lblIDUsuario))
                    .addContainerGap(1246, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbCodigo)
                        .addComponent(lblIDUsuario))
                    .addContainerGap(471, Short.MAX_VALUE)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/acima-logo-200p.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(402, 402, 402)
                        .addComponent(lb_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lb_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/BackgroundNew.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(lblFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(lblFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NroCotizacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroCotizacionKeyPressed
        try {
            String query = queryTabla
                    + "where rec.IDCotizacion like ?";
            String ID = txt_NroCotizacion.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, "%" + ID + "%");
            ResultSet rs = pst.executeQuery();
            tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            ocultarAjustarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_NroCotizacionKeyPressed

    private void RdBtn_exactaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtn_exactaActionPerformed
        if (RdBtn_exacta.isSelected()) {
            jDateExacta.setVisible(true);
            jDateExacta.setEnabled(true);
            btn_Buscar_Exacto.setVisible(true);
            btn_Buscar_Exacto.setEnabled(true);

            JDateRango1.setVisible(false);
            JDateRango1.setEnabled(false);
            JDateRango2.setVisible(false);
            JDateRango2.setEnabled(false);
            btn_Buscar_Rango.setVisible(false);
            btn_Buscar_Rango.setEnabled(false);
            lbDesde.setVisible(false);
            lbHasta.setVisible(false);
        }
    }//GEN-LAST:event_RdBtn_exactaActionPerformed

    private void RdBtn_RangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtn_RangoActionPerformed
        if (RdBtn_Rango.isSelected()) {
            jDateExacta.setVisible(false);
            jDateExacta.setEnabled(false);
            btn_Buscar_Exacto.setVisible(false);
            btn_Buscar_Exacto.setEnabled(false);

            JDateRango1.setVisible(true);
            JDateRango1.setEnabled(true);
            JDateRango2.setVisible(true);
            JDateRango2.setEnabled(true);
            btn_Buscar_Rango.setVisible(true);
            btn_Buscar_Rango.setEnabled(true);
            lbDesde.setVisible(true);
            lbHasta.setVisible(true);
        }
    }//GEN-LAST:event_RdBtn_RangoActionPerformed

    private void btn_Buscar_ExactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Buscar_ExactoActionPerformed
        if (jDateExacta.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese una fecha para buscar.");
        } else {
            try {
                String query = queryTabla
                        + "where date_format(rec.fecha_recordatorioCobranza,'%d-%m-%Y') = ?";
                String fecha = ((JTextField) jDateExacta.getDateEditor().getUiComponent()).getText().substring(0, 10);
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setString(1, fecha);
                ResultSet rs = pst.executeQuery();
                tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
                ocultarAjustarTabla();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_Buscar_ExactoActionPerformed

    private void btn_Buscar_RangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Buscar_RangoActionPerformed
        if (JDateRango1.getDate() == null || JDateRango2.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese las 2 fechas para buscar.");
        } else {
            Calendar fecha_inicio = JDateRango1.getCalendar();
            Calendar fecha_fin = JDateRango2.getCalendar();
            if (fecha_fin.before(fecha_inicio)) {
                JOptionPane.showMessageDialog(null, "La fecha 'desde' es mayor a la fecha 'hasta'.");
            } else {
                try {
                    String query = queryTabla
                            + "where date_format(rec.fecha_recordatorioCobranza,'%d-%m-%Y') BETWEEN ? and ?";
                    String fecha_desde = ((JTextField) JDateRango1.getDateEditor().getUiComponent()).getText().substring(0, 10);
                    String fecha_hasta = ((JTextField) JDateRango2.getDateEditor().getUiComponent()).getText().substring(0, 10);
                    PreparedStatement pst = cn.prepareStatement(query);
                    pst.setString(1, fecha_desde);
                    pst.setString(2, fecha_hasta);
                    ResultSet rs = pst.executeQuery();
                    tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
                    ocultarAjustarTabla();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_Buscar_RangoActionPerformed

    private void txt_RutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RutKeyPressed
        try {
            String query = queryTabla
                    + "where cli.rut like ?";
            String rut = txt_Rut.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, "%" + rut + "%");
            ResultSet rs = pst.executeQuery();
            tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            ocultarAjustarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_RutKeyPressed

    private void txt_NombreConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreConKeyPressed
        try {
            String query = queryTabla
                    + "where cli.Nombre like ?";
            String Nombre = txt_NombreCon.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, "%" + Nombre + "%");
            ResultSet rs = pst.executeQuery();
            tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            ocultarAjustarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_NombreConKeyPressed

    private void txt_NombreOrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreOrgKeyPressed
        try {
            String query = queryTabla
                    + "where org.NombreOrganizacion like ?";
            String Nombre = txt_NombreOrg.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, "%" + Nombre + "%");
            ResultSet rs = pst.executeQuery();
            tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            ocultarAjustarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_NombreOrgKeyPressed

    private void cambioestado(int est) {
        try {
            String query = "";
            if (est != 0) {
                query = queryTabla
                        + "where rec.Estado = ?";
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setInt(1, est);
                ResultSet rs = pst.executeQuery();
                tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                query = queryTabla;
                PreparedStatement pst = cn.prepareStatement(query);
                ResultSet rs = pst.executeQuery();
                tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            }

            ocultarAjustarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void ActualizarTabla() {
        try {
            String query = queryTabla;
            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            ocultarAjustarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void cbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEstadoItemStateChanged
        int aux = cbEstado.getSelectedIndex();
        cambioestado(aux);
    }//GEN-LAST:event_cbEstadoItemStateChanged

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        if (tblRecordatorio.getSelectedRow() != -1) {

            String respuesta = JOptionPane.showInputDialog(null, "Escriba Su codigo de autorización.", "Permisos de acción", JOptionPane.INFORMATION_MESSAGE);
            int id = Integer.parseInt(tblRecordatorio.getModel().getValueAt(tblRecordatorio.getSelectedRow(), 0).toString());

            if (lbCodigo.getText().equals(respuesta)) {
                JOptionPane.showMessageDialog(null, "Codigo de autorización Correcto.", "Correcto", JOptionPane.INFORMATION_MESSAGE);

                try {
                    String Comentario = "Se cambio el estado del recordatorio id nro." + id + " por el empleado con id nro. " + lblIDUsuario.getText();

                    String query = "INSERT INTO movimientosventas (IDUsuario,Movimiento) VALUES (?,?)";
                    PreparedStatement pst = cn.prepareStatement(query);
                    pst.setInt(1, Integer.parseInt(lblIDUsuario.getText()));
                    pst.setString(2, Comentario);
                    int up = pst.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                if (cbCambiarEstado.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Por favor Seleccione un estado valido");
                } else {
                    int estado = cbCambiarEstado.getSelectedIndex();
                    int ID = Integer.parseInt(tblRecordatorio.getModel().getValueAt(tblRecordatorio.getSelectedRow(), 0).toString());
                    try {
                        String query = "UPDATE recordatorio_cotizacion SET Estado = ? WHERE IDRecordatorio_cotizacion = ? ";
                        PreparedStatement update = cn.prepareStatement(query);
                        update.setInt(1, estado);
                        update.setInt(2, ID);
                        int i = update.executeUpdate();
                        JOptionPane.showMessageDialog(null, "El Estado se ha cambiado correctamente");
                        ActualizarTabla();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Codigo de autorizacion invalido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para proceder.");
        }
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void lblVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_lblVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordatorioCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordatorioCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordatorioCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordatorioCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordatorioCotizaciones().setVisible(true);
            }
        });
    }

    public void ocultarAjustarTabla() {
        //Se oculta la columna 0
        tblRecordatorio.getColumnModel().getColumn(0).setMaxWidth(0);
        tblRecordatorio.getColumnModel().getColumn(0).setMinWidth(0);
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        //ajuste de la columna 1
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(90);
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(1).setMinWidth(90);

        //ajuste de la columna 2
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(90);
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(2).setMinWidth(90);

        //ajuste de la columna 4
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(75);
        tblRecordatorio.getTableHeader().getColumnModel().getColumn(4).setMinWidth(75);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateRango1;
    private com.toedter.calendar.JDateChooser JDateRango2;
    private javax.swing.JRadioButton RdBtn_Rango;
    private javax.swing.JRadioButton RdBtn_exacta;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btn_Buscar_Exacto;
    private javax.swing.JButton btn_Buscar_Rango;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCambiarEstado;
    private javax.swing.JComboBox<String> cbEstado;
    private com.toedter.calendar.JDateChooser jDateExacta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnl_Cotización;
    private javax.swing.JPanel jPnl_Fecha;
    private javax.swing.JPanel jPnl_NombreCont;
    private javax.swing.JPanel jPnl_Organizacion;
    private javax.swing.JPanel jPnl_RespPen;
    private javax.swing.JPanel jPnl_RutOrganizacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDesde;
    private javax.swing.JLabel lbHasta;
    private javax.swing.JLabel lb_NombreCon;
    private javax.swing.JLabel lb_NombreOrg;
    private javax.swing.JLabel lb_Rut;
    private javax.swing.JLabel lb_SubTituloEstado;
    private javax.swing.JLabel lb_Titulo;
    private javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblIDUsuario;
    private javax.swing.JButton lblVolver;
    private javax.swing.JLabel ln_NroCotizacion;
    public javax.swing.JTable tblRecordatorio;
    private javax.swing.JTextField txt_NombreCon;
    private javax.swing.JTextField txt_NombreOrg;
    private javax.swing.JTextField txt_NroCotizacion;
    private javax.swing.JTextField txt_Rut;
    // End of variables declaration//GEN-END:variables
}
