package PlataformaVentas;

import clases.Conexion;
import clases.Operaciones;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Diego Alfaro Fierro, Diego González Romàn
 */
public class Status extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();
    String consultaTabla = "SELECT cot.IDCotizacion AS 'N° Cotizacion',\n"
            + "cli.Rut AS 'Rut',\n"
            + "org.NombreOrganizacion AS 'Organización',\n"
            + "cli.Nombre AS 'Contacto',\n"
            + "CONCAT('$',FORMAT(cot.bruto,0)) AS 'Total',\n"
            + "date_format(cot.FechaCotizacion,'%d-%m-%Y') AS 'Fecha Emision'\n"
            + "FROM cotizacion cot join usuario usr on cot.IDUsuario = usr.IDUsuario \n"
            + "join cliente cli on cli.idCliente = cot.idCliente\n"
            + "join organizacion org ON cli.IDOrganizacion = org.IDOrganizacion\n";

    public Status() {
        initComponents();
        Actualizar();
       
        jPanel2.setBackground(new Color(0, 0, 0, 30));

        jDateExacta.setVisible(true);
        jDateExacta.setEnabled(true);
        btn_Buscar_Exacto.setVisible(true);
        btn_Buscar_Exacto.setEnabled(true);
        JDateRango1.setVisible(false);
        JDateRango1.setEnabled(false);
        JDateRango2.setVisible(false);
        JDateRango2.setEnabled(false);
        btn_Buscar_Rango.setVisible(false);
        btn_Buscar_Rango.setEnabled(false);
        lbDesde.setVisible(false);
        lbHasta.setVisible(false);
    }

    public void AjusteTabla() {
        tblCotizacionesPendientes.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(100);
        tblCotizacionesPendientes.getTableHeader().getColumnModel().getColumn(0).setMinWidth(100);
        tblCotizacionesPendientes.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(100);
        tblCotizacionesPendientes.getTableHeader().getColumnModel().getColumn(1).setMinWidth(100);
        tblCotizacionesPendientes.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(120);
        tblCotizacionesPendientes.getTableHeader().getColumnModel().getColumn(4).setMinWidth(120);
    }

    public void Actualizar() {
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=?";
            String param = lblIDUsuario.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
            AjusteTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup_Fechas = new javax.swing.ButtonGroup();
        BtnGroup_Estado = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCotizacionesPendientes = new javax.swing.JTable();
        lblVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnGuardarRecordatorio = new javax.swing.JButton();
        jDateRecordatorio = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextObservacion = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPnl_Cotización = new javax.swing.JPanel();
        ln_NroCotizacion = new javax.swing.JLabel();
        txt_NroCotizacion = new javax.swing.JTextField();
        jPnl_Fecha = new javax.swing.JPanel();
        jDateExacta = new com.toedter.calendar.JDateChooser();
        RdBtn_exacta = new javax.swing.JRadioButton();
        RdBtn_Rango = new javax.swing.JRadioButton();
        btn_Buscar_Exacto = new javax.swing.JButton();
        JDateRango1 = new com.toedter.calendar.JDateChooser();
        JDateRango2 = new com.toedter.calendar.JDateChooser();
        btn_Buscar_Rango = new javax.swing.JButton();
        lbDesde = new javax.swing.JLabel();
        lbHasta = new javax.swing.JLabel();
        jPnl_RespPen = new javax.swing.JPanel();
        RdBtn_Respondidos = new javax.swing.JRadioButton();
        RdBtn_Pendientes = new javax.swing.JRadioButton();
        lb_SubTituloEstado = new javax.swing.JLabel();
        jPnl_RutOrganizacion = new javax.swing.JPanel();
        lb_Rut = new javax.swing.JLabel();
        txt_Rut = new javax.swing.JTextField();
        jPnl_NombreCont = new javax.swing.JPanel();
        lb_NombreCon = new javax.swing.JLabel();
        txt_NombreCon = new javax.swing.JTextField();
        jPnl_Organizacion = new javax.swing.JPanel();
        lb_NombreOrg = new javax.swing.JLabel();
        txt_NombreOrg = new javax.swing.JTextField();
        btnGestionarCotizacion = new javax.swing.JButton();
        btnRecordatorios = new javax.swing.JButton();
        lb_Titulo = new javax.swing.JLabel();
        Btn_OC = new javax.swing.JButton();
        lb_OC = new javax.swing.JLabel();
        lblIDUsuario = new javax.swing.JLabel();
        lblCredencial = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status de Cotización");
        setMaximumSize(new java.awt.Dimension(1280, 685));
        setMinimumSize(new java.awt.Dimension(1280, 685));
        setPreferredSize(new java.awt.Dimension(1280, 685));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 685));

        tblCotizacionesPendientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblCotizacionesPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCotizacionesPendientes.getTableHeader().setResizingAllowed(false);
        tblCotizacionesPendientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCotizacionesPendientes);

        lblVolver.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        lblVolver.setText("Volver");
        lblVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVolverActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGuardarRecordatorio.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnGuardarRecordatorio.setText("Guardar Recordatorio");
        btnGuardarRecordatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRecordatorioActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextObservacion);

        jLabel1.setText("Observación");

        jLabel2.setText("Fecha Recordatorio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarRecordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateRecordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateRecordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarRecordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jButton1.setText("Actualizar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ln_NroCotizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ln_NroCotizacion.setText("N° Cotización:");

        txt_NroCotizacion.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_NroCotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NroCotizacionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_CotizaciónLayout = new javax.swing.GroupLayout(jPnl_Cotización);
        jPnl_Cotización.setLayout(jPnl_CotizaciónLayout);
        jPnl_CotizaciónLayout.setHorizontalGroup(
            jPnl_CotizaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_CotizaciónLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(ln_NroCotizacion)
                .addGap(18, 18, 18)
                .addComponent(txt_NroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_CotizaciónLayout.setVerticalGroup(
            jPnl_CotizaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_CotizaciónLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_CotizaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln_NroCotizacion)
                    .addComponent(txt_NroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Numero Cotización", jPnl_Cotización);

        jPnl_Fecha.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jPnl_Fecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateExacta.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jDateExacta.setMaxSelectableDate(new java.util.Date(253370779308000L));
        jPnl_Fecha.add(jDateExacta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 270, -1));

        BtnGroup_Fechas.add(RdBtn_exacta);
        RdBtn_exacta.setSelected(true);
        RdBtn_exacta.setText("Fecha Exacta");
        RdBtn_exacta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtn_exactaActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(RdBtn_exacta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        BtnGroup_Fechas.add(RdBtn_Rango);
        RdBtn_Rango.setText("Rango de Fechas");
        RdBtn_Rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtn_RangoActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(RdBtn_Rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        btn_Buscar_Exacto.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn_Buscar_Exacto.setText("Buscar");
        btn_Buscar_Exacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Buscar_ExactoActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(btn_Buscar_Exacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));

        JDateRango1.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jPnl_Fecha.add(JDateRango1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 270, -1));

        JDateRango2.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jPnl_Fecha.add(JDateRango2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 270, -1));

        btn_Buscar_Rango.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn_Buscar_Rango.setText("Buscar");
        btn_Buscar_Rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Buscar_RangoActionPerformed(evt);
            }
        });
        jPnl_Fecha.add(btn_Buscar_Rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));

        lbDesde.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbDesde.setText("Desde:");
        jPnl_Fecha.add(lbDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lbHasta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbHasta.setText(" Hasta:");
        jPnl_Fecha.add(lbHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jTabbedPane2.addTab("FechaEmitida", jPnl_Fecha);

        BtnGroup_Estado.add(RdBtn_Respondidos);
        RdBtn_Respondidos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        RdBtn_Respondidos.setText("Cotizaciones Respondidas");
        RdBtn_Respondidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtn_RespondidosActionPerformed(evt);
            }
        });

        BtnGroup_Estado.add(RdBtn_Pendientes);
        RdBtn_Pendientes.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        RdBtn_Pendientes.setText("Cotizaciones Pendientes");
        RdBtn_Pendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBtn_PendientesActionPerformed(evt);
            }
        });

        lb_SubTituloEstado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lb_SubTituloEstado.setText("Estado de las Cotizaciones:");

        javax.swing.GroupLayout jPnl_RespPenLayout = new javax.swing.GroupLayout(jPnl_RespPen);
        jPnl_RespPen.setLayout(jPnl_RespPenLayout);
        jPnl_RespPenLayout.setHorizontalGroup(
            jPnl_RespPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_RespPenLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lb_SubTituloEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_RespPenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnl_RespPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdBtn_Respondidos)
                    .addComponent(RdBtn_Pendientes))
                .addGap(176, 176, 176))
        );
        jPnl_RespPenLayout.setVerticalGroup(
            jPnl_RespPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_RespPenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_SubTituloEstado)
                .addGap(18, 18, 18)
                .addComponent(RdBtn_Respondidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdBtn_Pendientes)
                .addGap(12, 12, 12))
        );

        jTabbedPane2.addTab("Repondidas o Pendientes", jPnl_RespPen);

        lb_Rut.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lb_Rut.setText("Rut:");

        txt_Rut.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_RutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_RutOrganizacionLayout = new javax.swing.GroupLayout(jPnl_RutOrganizacion);
        jPnl_RutOrganizacion.setLayout(jPnl_RutOrganizacionLayout);
        jPnl_RutOrganizacionLayout.setHorizontalGroup(
            jPnl_RutOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_RutOrganizacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_Rut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPnl_RutOrganizacionLayout.setVerticalGroup(
            jPnl_RutOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_RutOrganizacionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_RutOrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Rut)
                    .addComponent(txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Rut Organización", jPnl_RutOrganizacion);

        lb_NombreCon.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lb_NombreCon.setText("Nombre Contacto:");

        txt_NombreCon.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_NombreCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NombreConKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_NombreContLayout = new javax.swing.GroupLayout(jPnl_NombreCont);
        jPnl_NombreCont.setLayout(jPnl_NombreContLayout);
        jPnl_NombreContLayout.setHorizontalGroup(
            jPnl_NombreContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NombreContLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lb_NombreCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_NombreContLayout.setVerticalGroup(
            jPnl_NombreContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NombreContLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_NombreContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NombreCon)
                    .addComponent(txt_NombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nombre Contacto", jPnl_NombreCont);

        lb_NombreOrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lb_NombreOrg.setText("Nombre Organización:");

        txt_NombreOrg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txt_NombreOrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NombreOrgKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_OrganizacionLayout = new javax.swing.GroupLayout(jPnl_Organizacion);
        jPnl_Organizacion.setLayout(jPnl_OrganizacionLayout);
        jPnl_OrganizacionLayout.setHorizontalGroup(
            jPnl_OrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_OrganizacionLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lb_NombreOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_NombreOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_OrganizacionLayout.setVerticalGroup(
            jPnl_OrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_OrganizacionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl_OrganizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NombreOrg)
                    .addComponent(txt_NombreOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Organización", jPnl_Organizacion);

        btnGestionarCotizacion.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnGestionarCotizacion.setText("Gestionar Cotización");
        btnGestionarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCotizacionActionPerformed(evt);
            }
        });

        btnRecordatorios.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnRecordatorios.setText("Ver recordatorios");
        btnRecordatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordatoriosActionPerformed(evt);
            }
        });

        lb_Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lb_Titulo.setText("Status de Cotización");

        Btn_OC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/mercado-público_.png"))); // NOI18N
        Btn_OC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OCActionPerformed(evt);
            }
        });

        lb_OC.setFont(new java.awt.Font("Century", 0, 20)); // NOI18N
        lb_OC.setText("Consultar Órdenes de Compra");

        lblIDUsuario.setVisible(false);

        lblCredencial.setVisible(false);

        lbCodigo.setVisible(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/acima-logo-200p.png"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(386, 386, 386)
                .addComponent(lb_Titulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_OC, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lb_OC))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbCodigo)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(340, 340, 340)
                            .addComponent(lblIDUsuario))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(lblCredencial)))
                    .addGap(872, 872, 872)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lb_Titulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnRecordatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGestionarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Btn_OC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lb_OC)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbCodigo)
                    .addGap(60, 60, 60)
                    .addComponent(lblIDUsuario)
                    .addGap(40, 40, 40)
                    .addComponent(lblCredencial)
                    .addContainerGap(524, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlataformaVentas/Imagenes/BackgroundNew.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 691, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Fondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_lblVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Actualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RdBtn_exactaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtn_exactaActionPerformed
        if (RdBtn_exacta.isSelected()) {
            jDateExacta.setVisible(true);
            jDateExacta.setEnabled(true);
            btn_Buscar_Exacto.setVisible(true);
            btn_Buscar_Exacto.setEnabled(true);

            JDateRango1.setVisible(false);
            JDateRango1.setEnabled(false);
            JDateRango2.setVisible(false);
            JDateRango2.setEnabled(false);
            btn_Buscar_Rango.setVisible(false);
            btn_Buscar_Rango.setEnabled(false);
            lbDesde.setVisible(false);
            lbHasta.setVisible(false);
        }
    }//GEN-LAST:event_RdBtn_exactaActionPerformed

    private void RdBtn_RangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtn_RangoActionPerformed
        if (RdBtn_Rango.isSelected()) {
            jDateExacta.setVisible(false);
            jDateExacta.setEnabled(false);
            btn_Buscar_Exacto.setVisible(false);
            btn_Buscar_Exacto.setEnabled(false);

            JDateRango1.setVisible(true);
            JDateRango1.setEnabled(true);
            JDateRango2.setVisible(true);
            JDateRango2.setEnabled(true);
            btn_Buscar_Rango.setVisible(true);
            btn_Buscar_Rango.setEnabled(true);
            lbDesde.setVisible(true);
            lbHasta.setVisible(true);
        }
    }//GEN-LAST:event_RdBtn_RangoActionPerformed

    private void RdBtn_RespondidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtn_RespondidosActionPerformed
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=? and cot.respondido = 'Respondido' ";
            String param = lblIDUsuario.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_RdBtn_RespondidosActionPerformed

    private void RdBtn_PendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBtn_PendientesActionPerformed
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=? and cot.respondido = 'No Respondido' ";
            String param = lblIDUsuario.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_RdBtn_PendientesActionPerformed

    private void txt_NroCotizacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroCotizacionKeyPressed
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=?  and cot.IDCotizacion like ?";
            String param = lblIDUsuario.getText();
            String ID = txt_NroCotizacion.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            pst.setString(2, "%" + ID + "%");
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_NroCotizacionKeyPressed

    private void txt_NombreOrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreOrgKeyPressed
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=?  and org.NombreOrganizacion like ?";
            String param = lblIDUsuario.getText();
            String Nombre = txt_NombreOrg.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            pst.setString(2, "%" + Nombre + "%");
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_NombreOrgKeyPressed

    private void txt_NombreConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreConKeyPressed
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=?  and cli.Nombre like ?";
            String param = lblIDUsuario.getText();
            String Nombre = txt_NombreCon.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            pst.setString(2, "%" + Nombre + "%");
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_NombreConKeyPressed

    private void txt_RutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RutKeyPressed
        try {
            String query = consultaTabla
                    + "where cot.idUsuario=?  and cli.rut like ?";
            String param = lblIDUsuario.getText();
            String rut = txt_Rut.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            pst.setString(2, "%" + rut + "%");
            ResultSet rs = pst.executeQuery();
            tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txt_RutKeyPressed

    private void btn_Buscar_ExactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Buscar_ExactoActionPerformed
        if (jDateExacta.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese una fecha para buscar.");
        } else {
            try {
                String query = consultaTabla
                        + "where cot.idUsuario=?  and date_format(cot.FechaCotizacion,'%d-%m-%Y') = ?";
                String param = lblIDUsuario.getText();
                String fecha = ((JTextField) jDateExacta.getDateEditor().getUiComponent()).getText().substring(0, 10);
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setString(1, param);
                pst.setString(2, fecha);
                ResultSet rs = pst.executeQuery();
                tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_Buscar_ExactoActionPerformed

    private void btn_Buscar_RangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Buscar_RangoActionPerformed
        if (JDateRango1.getDate() == null || JDateRango2.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese las 2 fechas para buscar.");
        } else {
            Calendar fecha_inicio = JDateRango1.getCalendar();
            Calendar fecha_fin = JDateRango2.getCalendar();
            if (fecha_fin.before(fecha_inicio)) {
                JOptionPane.showMessageDialog(null, "La fecha 'desde' es mayor a la fecha 'hasta'.");
            } else {
                try {
                    String query = consultaTabla
                            + "where cot.idUsuario=?  and date_format(cot.FechaCotizacion,'%d-%m-%Y') BETWEEN ? and ?";
                    String param = lblIDUsuario.getText();
                    String fecha_desde = ((JTextField) JDateRango1.getDateEditor().getUiComponent()).getText().substring(0, 10);
                    String fecha_hasta = ((JTextField) JDateRango2.getDateEditor().getUiComponent()).getText().substring(0, 10);
                    PreparedStatement pst = cn.prepareStatement(query);
                    pst.setString(1, param);
                    pst.setString(2, fecha_desde);
                    pst.setString(3, fecha_hasta);
                    ResultSet rs = pst.executeQuery();
                    tblCotizacionesPendientes.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_Buscar_RangoActionPerformed

    private void btnGestionarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCotizacionActionPerformed
        try {
            int id = Integer.parseInt(tblCotizacionesPendientes.getModel().getValueAt(tblCotizacionesPendientes.getSelectedRow(), 0).toString());
            String query = "select cot.idCotizacion,\n"
                    + "dis.nombreDistribuidor,\n"
                    + "cli.Nombre,\n"
                    + "cli.rut,\n"
                    + "cli.Razon_social,\n"
                    + "cli.Cargo,\n"
                    + "cot.netototal,\n"
                    + "cot.ivaTotal,\n"
                    + "cot.Bruto,\n"
                    + "cot.Respondido,\n"
                    + "cot.FechaCotizacion\n"
                    + "from detallecotizacion det\n"
                    + "left join cotizacion cot on det.idCotizacion = cot.idCotizacion\n"
                    + "left join producto pro on det.idProducto = pro.ID\n"
                    + "left join distribuidor dis on pro.idDistribuidor = dis.idDistribuidor\n"
                    + "left join cliente cli on cot.IDCliente = cli.IDCliente \n"
                    + "where cot.idCotizacion=?";
            PreparedStatement pst2 = cn.prepareStatement(query);
            pst2.setInt(1, id);
            ResultSet rs2 = pst2.executeQuery();
            if (rs2.next()) {
                int idCot = rs2.getInt("IDCotizacion");
                String distri = rs2.getString("nombreDistribuidor");
                String nombre = rs2.getString("Nombre");
                String rut = rs2.getString("Rut");
                String razon = rs2.getString("Razon_social");
                String cargo = rs2.getString("Cargo");
                int neto = rs2.getInt("netototal");
                int iva = rs2.getInt("ivaTotal");
                int bruto = rs2.getInt("Bruto");
                String respondido = rs2.getString("Respondido");
                String FechaEmision = rs2.getString("FechaCotizacion");

                DatosCotizacion DatCot = new DatosCotizacion();
                DatCot.txtID.setText(String.valueOf(idCot));
                DatCot.txtDistribuidor.setText(distri);
                DatCot.txtNombre.setText(nombre);
                DatCot.txtRut.setText(rut);
                DatCot.txtRazonSocial.setText(razon);
                DatCot.txtCargo.setText(cargo);
                DatCot.txtNeto.setText(String.valueOf(neto));
                DatCot.txtIva.setText(String.valueOf(iva));
                DatCot.txtTotal.setText(String.valueOf(bruto));
                DatCot.lbCodigo.setText(lbCodigo.getText());
                DatCot.lblIDUsuario.setText(lblIDUsuario.getText());

                if (respondido.equals("Respondido")) {
                    DatCot.cbStatus.setSelectedIndex(1);
                } else if (respondido.equals("No Respondido")) {
                    DatCot.cbStatus.setSelectedIndex(0);
                }
                DatCot.txtFecha.setText(FechaEmision);

                query = "select pro.idproducto 'ID Producto',\n"
                        + "con.NombreConvenio 'Convenio Marco',\n"
                        + "pro.Producto 'Nombre del Producto',\n"
                        + "pro.sku 'SKU',\n"
                        + "pro.PrecioVenta 'Precio',\n"
                        + "det.cantidad,\n"
                        + "det.neto,\n"
                        + "det.Cargo,\n"
                        + "det.descuento,\n"
                        + "det.total\n"
                        + "from detallecotizacion det\n"
                        + "left join cotizacion cot on det.idCotizacion = cot.idCotizacion\n"
                        + "left join producto pro on det.idProducto = pro.ID\n"
                        + "left join conveniomarco con on pro.CodigoConvenio = con.codigoConvenio\n"
                        + "where cot.idCotizacion=?";
                pst2 = cn.prepareStatement(query);
                pst2.setInt(1, id);
                ResultSet rs = pst2.executeQuery();
                DatCot.tblDetalle.setModel(DbUtils.resultSetToTableModel(rs));
                DatCot.show();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una cotización "+e.getMessage());
        }

    }//GEN-LAST:event_btnGestionarCotizacionActionPerformed

    private void btnGuardarRecordatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRecordatorioActionPerformed
        if (tblCotizacionesPendientes.getSelectedRow() != -1) {

            String respuesta = JOptionPane.showInputDialog(null, "Escriba Su codigo de autorización.", "Permisos de acción", JOptionPane.INFORMATION_MESSAGE);
            int id = Integer.parseInt(tblCotizacionesPendientes.getModel().getValueAt(tblCotizacionesPendientes.getSelectedRow(), 0).toString());

            if (lbCodigo.getText().equals(respuesta)) {
                JOptionPane.showMessageDialog(null, "Codigo de autorización Correcto.", "Correcto", JOptionPane.INFORMATION_MESSAGE);

                try {
                    String Comentario = "Se creo un recordatorio para la cotizacion id nro." + id + " por el empleado con id nro. " + lblIDUsuario.getText();

                    String query = "INSERT INTO movimientosventas (IDUsuario,Movimiento) VALUES (?,?)";
                    PreparedStatement pst = cn.prepareStatement(query);
                    pst.setInt(1, Integer.parseInt(lblIDUsuario.getText()));
                    pst.setString(2, Comentario);
                    int up = pst.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                try {
                    String observacion = jTextObservacion.getText();

                    jDateRecordatorio.setDateFormatString("yyyy-MM-dd");
                    String fec = ((JTextField) jDateRecordatorio.getDateEditor().getUiComponent()).getText().substring(0, 10);

                    String query = "insert into recordatorio_cotizacion (fecha_recordatorioCobranza, observacion, IDCotizacion, Estado) VALUES (?, ?, ?, 1)";
                    PreparedStatement pst = cn.prepareStatement(query);
                    pst.setString(1, fec);
                    pst.setString(2, observacion);
                    pst.setInt(3, id);
                    int up = pst.executeUpdate();
                    jDateRecordatorio.setDateFormatString("dd-MM-yyyy");
                    JOptionPane.showMessageDialog(null, "Recordatorio guardado.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Codigo de autorizacion invalido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para proceder.");
        }
    }//GEN-LAST:event_btnGuardarRecordatorioActionPerformed

    private void btnRecordatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordatoriosActionPerformed
        try {
            RecordatorioCotizaciones rec = new RecordatorioCotizaciones();

            String query = "select rec.IDRecordatorio_cotizacion AS 'ID Recordatorio',\n"
                    + "rec.IDCotizacion as 'ID cotización',\n"
                    + "DATE_FORMAT(rec.fecha_recordatorioCobranza, '%d-%m-%Y') as 'Fecha Venc.',\n"
                    + "rec.observacion as 'Observacion',\n"
                    + "(CASE\n"
                    + "WHEN rec.Estado = 1 THEN 'Por vencer'\n"
                    + "WHEN rec.Estado = 2 THEN 'Realizado'\n"
                    + "WHEN rec.Estado = 3 THEN 'Vencido'\n"
                    + "END) AS 'Estado'\n"
                    + "from recordatorio_cotizacion rec JOIN cotizacion cot on cot.IDCotizacion = rec.IDCotizacion\n"
                    + "JOIN cliente cli ON cli.idCliente = cot.idCliente\n"
                    + "JOIN organizacion org ON cli.IDOrganizacion = org.IDOrganizacion\n";
            PreparedStatement pst = cn.prepareStatement(query);;
            ResultSet rs = pst.executeQuery();
            rec.tblRecordatorio.setModel(DbUtils.resultSetToTableModel(rs));
            rec.ocultarAjustarTabla();
            rec.lblIDUsuario.setText(lblIDUsuario.getText());
            rec.lbCodigo.setText(lbCodigo.getText());
            rec.show();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnRecordatoriosActionPerformed

    private void Btn_OCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OCActionPerformed
        try {
            ConsultarOrdenCompra con = new ConsultarOrdenCompra();
            Operaciones ope = new Operaciones();

            String query = ope.getConsultarOC();
            PreparedStatement pst = cn.prepareStatement(query);;
            ResultSet rs = pst.executeQuery();
            con.tbl_OC.setModel(DbUtils.resultSetToTableModel(rs));
            con.lblIDUsuario.setText(lblIDUsuario.getText());
            con.lbCodigo.setText(lbCodigo.getText());

            ope.OcultarColumnsOC(con.tbl_OC);
            con.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_Btn_OCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroup_Estado;
    private javax.swing.ButtonGroup BtnGroup_Fechas;
    private javax.swing.JButton Btn_OC;
    private javax.swing.JLabel Fondo;
    private com.toedter.calendar.JDateChooser JDateRango1;
    private com.toedter.calendar.JDateChooser JDateRango2;
    private javax.swing.JRadioButton RdBtn_Pendientes;
    private javax.swing.JRadioButton RdBtn_Rango;
    private javax.swing.JRadioButton RdBtn_Respondidos;
    private javax.swing.JRadioButton RdBtn_exacta;
    private javax.swing.JButton btnGestionarCotizacion;
    private javax.swing.JButton btnGuardarRecordatorio;
    private javax.swing.JButton btnRecordatorios;
    private javax.swing.JButton btn_Buscar_Exacto;
    private javax.swing.JButton btn_Buscar_Rango;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateExacta;
    private com.toedter.calendar.JDateChooser jDateRecordatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnl_Cotización;
    private javax.swing.JPanel jPnl_Fecha;
    private javax.swing.JPanel jPnl_NombreCont;
    private javax.swing.JPanel jPnl_Organizacion;
    private javax.swing.JPanel jPnl_RespPen;
    private javax.swing.JPanel jPnl_RutOrganizacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextPane jTextObservacion;
    public javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDesde;
    private javax.swing.JLabel lbHasta;
    private javax.swing.JLabel lb_NombreCon;
    private javax.swing.JLabel lb_NombreOrg;
    private javax.swing.JLabel lb_OC;
    private javax.swing.JLabel lb_Rut;
    private javax.swing.JLabel lb_SubTituloEstado;
    private javax.swing.JLabel lb_Titulo;
    public javax.swing.JLabel lblCredencial;
    public javax.swing.JLabel lblIDUsuario;
    private javax.swing.JButton lblVolver;
    private javax.swing.JLabel ln_NroCotizacion;
    public javax.swing.JTable tblCotizacionesPendientes;
    private javax.swing.JTextField txt_NombreCon;
    private javax.swing.JTextField txt_NombreOrg;
    private javax.swing.JTextField txt_NroCotizacion;
    private javax.swing.JTextField txt_Rut;
    // End of variables declaration//GEN-END:variables
}
